name: Generate 3P

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setting up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          
      - name: Run Script
        run: |
          python tools/generate3PAllTeams.py
          
      - name: Commit scrapping
        run: |
          git config --global user.name 'guilhermetheis'
          git config --global user.email 'guilhermetheis15@gmail.com'
          git add .
          git commit -am "Update the 3P CSV"
          git push
